version: '3'

networks:
  web:
    driver: bridge

services:
  app:
    build:
      context: ./docker/app
      dockerfile: Dockerfile
    platform: linux/x86_64
    image: restapi-app
    restart: unless-stopped
    working_dir: /var/www
    depends_on:
      - database
    ports:
      - "9000:9000"
    volumes:
      - ./:/var/www
      - ./docker/data/logs/php:/var/log/php
    #environment:
      #DATABASE_URL: postgresql://${POSTGRES_USER:-app}:${POSTGRES_PASSWORD:-!ChangeMe!}@database:5432/${POSTGRES_DB:-app}?serverVersion=${POSTGRES_VERSION:-15}&charset=${POSTGRES_CHARSET:-utf8}
    networks:
      - web

  database:
    image: postgres:${POSTGRES_VERSION:-15}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
      POSTGRES_USER: ${POSTGRES_USER:-app}
    volumes:
      - ./docker/data/db:/var/lib/postgresql/data:rw
    ports:
      - "5432:5432"
    networks:
      - web

  nginx:
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - ./:/var/www
      - ./docker/data/logs/nginx:/var/log/nginx
    ports:
      - "80:80"
      - "443:443"
    networks:
      - web

